version: '3'
services:
  db:
    image: postgres
    environment:
        - POSTGRES_HOST_AUTH_METHOD=trust
  web:
    build: .
    command: bundle exec rails s -p 3333 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3333:3333"
    depends_on:
      - db